 Q.1 Create two 3×3 matrices using the random function in Numpy and perform the following operations.
 Product (prod)
 Multiplication (multiply)
 Dot Product (dot)


In [11]:
import numpy as np

matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(10, size=(3, 3))

print("----------------------------------------------------")
print("Matrix 1:")
print(matrix_1)
print("----------------------------------------------------")
print("Matrix 2:")
print(matrix_2)
print("----------------------------------------------------")
product = np.prod(matrix_1, axis=0) * np.prod(matrix_2, axis=1)
print("Product:")
print(product)
print("----------------------------------------------------")
multiplication = matrix_1 * matrix_2
print("Multiplication:")
print(multiplication)
print("----------------------------------------------------")
dot_product = np.dot(matrix_1, matrix_2)
print("Dot Product:")
print(dot_product)
print("----------------------------------------------------")

----------------------------------------------------
Matrix 1:
[[2 6 6]
 [6 1 6]
 [0 7 8]]
----------------------------------------------------
Matrix 2:
[[5 2 0]
 [5 2 9]
 [1 9 6]]
----------------------------------------------------
Product:
[    0  3780 15552]
----------------------------------------------------
Multiplication:
[[10 12  0]
 [30  2 54]
 [ 0 63 48]]
----------------------------------------------------
Dot Product:
[[ 46  70  90]
 [ 41  68  45]
 [ 43  86 111]]
----------------------------------------------------


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR

In [12]:
import numpy as np

set_1 = np.array([1, 2, 3, 4, 5])
set_2 = np.array([3, 4, 5, 6, 7])


union = np.union1d(set_1, set_2)
print("Union:")
print(union)

intersection = np.intersect1d(set_1, set_2)
print("Intersection:")
print(intersection)

difference = np.setdiff1d(set_1, set_2)
print("Set difference:")
print(difference)

xor = np.setxor1d(set_1, set_2)
print("XOR:")
print(xor)

Union:
[1 2 3 4 5 6 7]
Intersection:
[3 4 5]
Set difference:
[1 2]
XOR:
[1 2 6 7]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array

In [13]:
import numpy as np

array = np.random.randint(10, size=10)

print("Original array:")
print(array)

cumulative_sum = np.cumsum(array)
print("Cumulative sum:")
print(cumulative_sum)

cumulative_product = np.cumprod(array)
print("Cumulative product:")
print(cumulative_product)

discrete_difference = np.diff(array, n=3)
print("Discrete difference (with n=3):")
print(discrete_difference)

unique_elements = np.unique(array)
print("Unique elements:")
print(unique_elements)

Original array:
[0 2 8 5 3 3 8 1 7 7]
Cumulative sum:
[ 0  2 10 15 18 21 29 30 37 44]
Cumulative product:
[0 0 0 0 0 0 0 0 0 0]
Discrete difference (with n=3):
[-13  10   1   3 -17  25 -19]
Unique elements:
[0 1 2 3 5 7 8]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [14]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Addition using zip()
result_zip = np.array([a + b for a, b in zip(array1, array2)])

# Addition using np.add()
result_np_add = np.add(array1, array2)

# User-defined addition function
def user_defined_add(x, y):
    return x + y

# Create a ufunc from the user-defined function
ufunc = np.frompyfunc(user_defined_add, 2, 1)

# Addition using the user-defined function
result_user_defined = ufunc(array1, array2)

# Print the results
print("Array 1:", array1)
print("Array 2:", array2)
print("\nAddition using zip():", result_zip)
print("Addition using np.add():", result_np_add)
print("Addition using user-defined function:", result_user_defined)

Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Addition using zip(): [11 22 33 44 55]
Addition using np.add(): [11 22 33 44 55]
Addition using user-defined function: [11 22 33 44 55]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [15]:
from functools import reduce

def lcm(numbers):
  """Find the least common multiple of a list of numbers."""
  def gcd(a, b):
    while b:
      a, b = b, a % b
    return a
  result = numbers[0]
  for number in numbers[1:]:
    result = result * number // gcd(result, number)
  return result

def gcd(numbers):
  """Find the greatest common divisor of a list of numbers."""
  def lcm(a, b):
    while b:
      a, b = b, a % b
    return a
  result = numbers[0]
  for number in numbers[1:]:
    result = lcm(result, number)
  return result

def main():
  numbers = [10, 20, 30]
  print("The LCM of", numbers, "is", lcm(numbers))
  print("The GCD of", numbers, "is", gcd(numbers))

if __name__ == "__main__":
  main()


The LCM of [10, 20, 30] is 60
The GCD of [10, 20, 30] is 10
