Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original Array:\n ", arr)
element_1 = arr[0, 1]  
print("\n Array Indexing - Accessing a single element:")
print(element_1)


slice_1 = arr[1:3, 0:2] 
print("\nArray Indexing - Accessing a slice:")
print(slice_1)

row_indices = np.array([0, 2])
col_indices = np.array([0, 2])
elements = arr[row_indices, col_indices]
print("\nFancy Indexing - Accessing elements using arrays of indices:")
print(elements)

bool_indices = arr > 4
filtered_elements = arr[bool_indices]
print("\nFancy Indexing - Using boolean arrays for filtering:")
print(filtered_elements)


Original Array:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Array Indexing - Accessing a single element:
2

Array Indexing - Accessing a slice:
[[4 5]
 [7 8]]

Fancy Indexing - Accessing elements using arrays of indices:
[1 9]

Fancy Indexing - Using boolean arrays for filtering:
[5 6 7 8 9]


Q2. Execute the 2D array Slicing.

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])


print("Original array:\n ", arr)

sliced_rows = arr[1:3, :]
print("\n Sliced Rows:")
print(sliced_rows)

sliced_cols = arr[:, 1:3]
print("\nSliced Columns:")
print(sliced_cols)

submatrix = arr[1:3, 1:3]
print("\nSliced Submatrix:")
print(submatrix)


Original array:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Sliced Rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Columns:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Sliced Submatrix:
[[ 6  7]
 [10 11]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [10]:
import numpy as np

five_dim_array = np.array([1, 2, 3, 4, 5], ndmin=5)
print(five_dim_array)

print("Shape of the 5-dimensional array:", five_dim_array.shape)


[[[[[1 2 3 4 5]]]]]
Shape of the 5-dimensional array: (1, 1, 1, 1, 5)


Q4. Reshape the array from 1-D to 2-D array.

In [1]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape(2, 3)

print(reshaped_array)


[[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_array = np.stack((arr1, arr2), axis=0)

hstacked_array = np.hstack((arr1, arr2))

vstacked_array = np.vstack((arr1, arr2))

dstacked_array = np.dstack((arr1, arr2))

print("Stacked Array using np.stack():")
print(stacked_array)
print("\nHorizontally Stacked Array using np.hstack():")
print(hstacked_array)
print("\nVertically Stacked Array using np.vstack():")
print(vstacked_array)
print("\nDepth-wise Stacked Array using np.dstack():")
print(dstacked_array)


Stacked Array using np.stack():
[[1 2 3]
 [4 5 6]]

Horizontally Stacked Array using np.hstack():
[1 2 3 4 5 6]

Vertically Stacked Array using np.vstack():
[[1 2 3]
 [4 5 6]]

Depth-wise Stacked Array using np.dstack():
[[[1 4]
  [2 5]
  [3 6]]]


Q6. Perform the searchsort method in Numpy array.

In [13]:
import numpy as np

sorted_array = np.array([1, 3, 4, 7, 9, 12])
value = 5

index_to_insert = np.searchsorted(sorted_array, value)
print(f"The value {value} should be inserted at index {index_to_insert} to maintain sorting.")


The value 5 should be inserted at index 3 to maintain sorting.


Q7. Create Numpy Structured array using your domain features.

In [28]:
import numpy as np


student_dtype = np.dtype([
    ('student_id', 'int32'),
    ('student_name', 'U50'),
    ('student_age', 'int32'),
])

course_dtype = np.dtype([
    ('course_id', 'int32'),
    ('course_name', 'U50'),
    ('course_credits', 'float64'),
])


enrollment_dtype = np.dtype([
    ('student_id', 'int32'),
    ('course_id', 'int32'),
    ('date', 'datetime64[D]'),
])


students = np.array([
    (1, 'Ansh', 20),
    (2, 'Adhish', 22),
    (3, 'Anurag', 21),
], dtype=student_dtype)

courses = np.array([
    (101, 'COD', 3.0),
    (102, 'Python', 4.0),
    (103, 'C', 3.5),
], dtype=course_dtype)

enrollments = np.array([
    (1, 101,'2023-09-15'),
    (2, 102,'2023-09-16'),
    (3, 103,'2023-09-05'),
], dtype=enrollment_dtype)

print("Student Information:")
print(students)
print("\nCourse Information:")
print(courses)
print("\nEnrollment Information:")
print(enrollments)


Student Information:
[(1, 'Ansh', 20) (2, 'Adhish', 22) (3, 'Anurag', 21)]

Course Information:
[(101, 'COD', 3. ) (102, 'Python', 4. ) (103, 'C', 3.5)]

Enrollment Information:
[(1, 101, '2023-09-15') (2, 102, '2023-09-16') (3, 103, '2023-09-05')]


Q8. Create Data frame using List and Dictionary.

In [20]:
import pandas as pd


students_data = [
    {'student_id': 1, 'student_name': 'Alice', 'student_age': 20},
    {'student_id': 2, 'student_name': 'Bob', 'student_age': 22},
    {'student_id': 3, 'student_name': 'Charlie', 'student_age': 21}
]

courses_data = [
    {'course_id': 101, 'course_name': 'Math', 'course_credits': 3.0},
    {'course_id': 102, 'course_name': 'Physics', 'course_credits': 4.0},
    {'course_id': 103, 'course_name': 'History', 'course_credits': 3.5}
]

students_df = pd.DataFrame(students_data)
courses_df = pd.DataFrame(courses_data)

print("Students DataFrame:")
print(students_df)

print("\nCourses DataFrame:")
print(courses_df)


Students DataFrame:
   student_id student_name  student_age
0           1        Alice           20
1           2          Bob           22
2           3      Charlie           21

Courses DataFrame:
   course_id course_name  course_credits
0        101        Math             3.0
1        102     Physics             4.0
2        103     History             3.5


In [ ]:
Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()


In [27]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, None, 30, 22, 28, 35, None, 27, None, 32],
    'Score': [95, 88, None, 75, None, 90, 82, None, 78, 94]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

missing_data = df.isnull()
print("\n1. Missing Data (True indicates missing data):\n")
print(missing_data)


non_missing_data = df.notnull()
print("\n2. Non-Missing Data (True indicates non-missing data):\n")
print(non_missing_data)


df_dropped = df.dropna()
print("\n3. DataFrame after using dropna():\n")
print(df_dropped)


df_filled = df.fillna({'Age': df['Age'].mean(), 'Score': df['Score'].median()})
print("\n4. DataFrame after using fillna():\n")
print(df_filled)


df_replaced = df.replace(np.nan, -1)
print("\n5. DataFrame after using replace():\n")
print(df_replaced)

df_interpolated = df.interpolate()
print("\n6. DataFrame after using interpolate():\n")
print(df_interpolated)


Original DataFrame:
      Name   Age  Score
0    Alice  25.0   95.0
1      Bob   NaN   88.0
2  Charlie  30.0    NaN
3    David  22.0   75.0
4      Eve  28.0    NaN
5    Frank  35.0   90.0
6    Grace   NaN   82.0
7    Helen  27.0    NaN
8      Ivy   NaN   78.0
9     Jack  32.0   94.0

1. Missing Data (True indicates missing data):

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False  False   True
5  False  False  False
6  False   True  False
7  False  False   True
8  False   True  False
9  False  False  False

2. Non-Missing Data (True indicates non-missing data):

   Name    Age  Score
0  True   True   True
1  True  False   True
2  True   True  False
3  True   True   True
4  True   True  False
5  True   True   True
6  True  False   True
7  True   True  False
8  True  False   True
9  True   True   True

3. DataFrame after using dropna():

    Name   Age  Score
0  Alice  25.0   95.0
3  David  22.0   75.0
5  Frank  35

Q10. Perform the Hierarchical Indexing in the above created dataset.

In [24]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, None, 30, 22, 28, 35, None, 27, None, 32],
    'Score': [95, 88, None, 75, None, 90, 82, None, 78, 94]
}

df = pd.DataFrame(data)


df.set_index(['Name', 'Age'], inplace=True)

print("DataFrame with Hierarchical Indexing:")
print(df)


DataFrame with Hierarchical Indexing:
              Score
Name    Age        
Alice   25.0   95.0
Bob     NaN    88.0
Charlie 30.0    NaN
David   22.0   75.0
Eve     28.0    NaN
Frank   35.0   90.0
Grace   NaN    82.0
Helen   27.0    NaN
Ivy     NaN    78.0
Jack    32.0   94.0
